on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '11'
          components: 'native-image'
      - run: ./gradlew nativeCompile
      - if: startsWith(matrix.os, 'macOS')
        run: echo "FILE_NAME=icicle-macos.zip" >> $GITHUB_ENV
      - if: startsWith(matrix.os, 'ubuntu')
        run: echo "FILE_NAME=icicle-linux.zip" >> $GITHUB_ENV
      - uses: Shopify/upload-to-release@v1
        with:
          name: ${{ env.FILE_NAME }}
          path: build/native/nativeCompile/icicle
          repo-token: ${{ secrets.GITHUB_TOKEN }}
