on:
  push:
    tags:
      - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '11'
          components: 'native-image'
      - run: ./gradlew nativeCompile
      - if: startsWith(matrix.os, 'macOS')
        run: echo "FILE_NAME=icicle-macos.zip" >> $GITHUB_ENV
      - if: startsWith(matrix.os, 'ubuntu')
        run: echo "FILE_NAME=icicle-linux.zip" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: build/native/nativeCompile/icicle
          filename: $FILE_NAME
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: $FILE_NAME
          token: ${{ secrets.GITHUB_TOKEN }}